Session initial
jitli98/CS497Project pull request #9
Opened 2020-10-29 18:01 UTC by dergoose

2020-10-29 18:25 UTC, Derpthemeus requested changes

2020-10-29 18:25 UTC, Derpthemeus commented on IdentityManagement/Sessions/session.ts
> +const jwtKey = "my_secret_key"
We should load this from an environment variable so that we don't need to commit the secret key to the public repo

2020-10-29 18:25 UTC, Derpthemeus commented on IdentityManagement/Sessions/session.ts
> +    const userId = req.body.userId
I think you need to configure body parsing before accessing the request body. See http://expressjs.com/en/resources/middleware/body-parser.html

2020-10-29 20:15 UTC, Derpthemeus approved these changes

2020-10-30 19:45 UTC, jitli98 commented on Sessions/session.ts
> +
Once you've setup your docker stuff, you can just communicate to my service here with the following url: **http://accounts:3000/login** and attach the username & password to the authorization header of the http request. You can take a look at my README to see what the response is so you can handle them appropriately in your own service.

2020-11-02 10:04 UTC, merged